from models.user_data import SpotifyUser
from models.track import Track
from google.generativeai import GenerativeModel, configure
import os
from dotenv import load_dotenv


load_dotenv()
gemini_api_key = os.getenv('GEMINI_API_KEY')
configure(api_key=gemini_api_key)


class PlaylistGeneratorAiModel:
    """
    Class for generating playlists using AI
    Communication with the Gemini AI model
    Supposed to generate list of tracks based on the description
    """
    def __init__(self, spotify: SpotifyUser = None):
        """
        :param spotify: SpotifyUser object
        """
        self.model = GenerativeModel()
        self.tracks = []
        self.sp = spotify.get_authorized_spotify_object()

    def generate_playlist(self, description: str, amount: int = 10):
        """
        Generate playlist based on the description
        :param description: description of the playlist style or mood
        :param amount: number of songs to generate
        :return: songs generated by the AI model in the form of a list
        """
        try:
            response = self.model.generate_content(
                f"Generate a playlist of songs for the following description: {description}. I want {amount} songs. "
                f"Please include ONLY song names. I want the response to be in the following form:\n"
                f"SongName1\nSongName2\nSongName3"
            )
            return response.text
        except Exception as e:
            print(f"Error generating playlist: {e}")
            return None

    def search_spotify(self, song_name: str) -> Track:
        """
        Search Spotify for a song
        :param song_name: given song name
        :return: Search results in the form of a Track object
        """
        try:
            results = self.sp.search(q=song_name, limit=1, type='track')
            if results and results['tracks']['items']:
                first_result = results['tracks']['items'][0]
                id = first_result['id']
                track = Track(id, self.sp)
                return track
            else:
                return None
        except Exception as e:
            print(f"Error searching Spotify: {e}")
            return None

    def create_playlist(self, description: str, amount: int):
        """
        Generate playlist based on the description
        Iterate over the generated songs and search for them in Spotify
        :param description: description of the playlist style or mood
        :param amount: number of songs to generate
        :return: playlist in the form of a list of Track objects
        """
        ai_playlist = self.generate_playlist(description, amount)
        if ai_playlist:
            songs = ai_playlist.split('\n')
            for song in songs:
                track = self.search_spotify(song.strip())
                if track:
                    self.tracks.append(track)
            return self.tracks
        else:
            return []
